# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class CardTransactionCategorization(str, Enum):
    Fraud = "Fraud"
    Normal = "Normal"
    Unknown = "Unknown"

class CardTransactionStatus(str, Enum):
    Pending = "Pending"
    Approved = "Approved"
    Declined = "Declined"
    Failed = "Failed"

# #########################################################################
# Generated classes (2)
# #########################################################################

class CardFraudDetectionResponse(BaseModel):
    reasons: typing.List[str]
    categorization: CardTransactionCategorization

class CardTransaction(BaseModel):
    id: str
    amount: float
    timestamp: str
    user_id: str
    card_number: str
    card_type: str
    card_issuer: str
    merchant_name: str
    location: str
    status: CardTransactionStatus

# #########################################################################
# Generated type aliases (0)
# #########################################################################
